#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/concourse-job-parameters-resource-request.XXXXXX)
cat > $payload <&0

url=$(jq -r '.source.url // ""' < $payload)

refs=$(curl $url | jq -r '[ .[] | { "ref" : .ref } ]')

jq -n "$refs" >&3
