#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/concourse-job-parameters-resource-request.XXXXXX)

url=$(jq -r '.source.url // ""' < $payload)

jq -n "[
  {\"ref\": \"$url\"}
]" >&3
