#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

payload=$(mktemp $TMPDIR/concourse-job-parameters-resource-request.XXXXXX)
cat > $payload <&0

last_ref=$(jq -r '.version.ref // ""' < $payload)

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

cd $destination

json=$(curl "https://gist.githubusercontent.com/$last_ref")

metas=$(echo $json | jq -r 'to_entries | map({name: .key, value: .value | tostring })')

json_keys=$(echo $json | jq -r 'keys[]')

while read -r key
do
  value=$(echo $json | jq -r ".$key")
  echo "$value" > $key
done <<< "$json_keys"

jq -n "{
  \"version\": {\"ref\": \"$last_ref\"},
  \"metadata\": $metas
}" >&3
